version: '3.8'

services:
  auction_sql_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-defaultuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-defaultpass}
      POSTGRES_DB: ${POSTGRES_DB:-defaultdb}
    volumes:
      - db_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${HOST_IP:-127.0.0.1}:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    network_mode: host
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: "my-kafka-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "${HOST_IP:-127.0.0.1}:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "127.0.0.1:2181"

  redis:
    image: redis:latest
    container_name: redis
    network_mode: host
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-defaultpass}

volumes:
  db_data: