name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH & Docker-Compose on Remote
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync project to remote
        run: |
          rsync -avz \
            --delete \
            --exclude '.git*' \
            -e "ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }}" \
            ./ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/docker/auction-system

      - name: Deploy on remote via SSH
        run: |
          ssh -i ~/.ssh/id_rsa -t -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /docker/auction-system/src

            docker compose pull
            docker compose build
            docker compose up -d --remove-orphans

            docker image prune -f
          EOF
